const gif = (file) => `images/gifs/${file}.gif`;
const moves = ["Protect", "Tera Blast", "Knock Off", "U-turn"];
const option = (name, file, types, accent, item = "@ Choice Band") => ({ name, item, image: gif(file), accent, types, moves });

// Les noms de fichiers correspondent aux GIF fournis / à ajouter dans images/gifs.
// Les suffixes X, Y et Z sont conservés exactement comme demandés.
const options = [
  option("Tapu Koko", "tapu koko", ["electric", "fairy"], "#ffe71c", "@ Light Clay"), option("Rillaboom", "rilaboom", ["grass"], "#83d85d", "@ Miracle Seed"), option("Archaludon", "archaludon", ["steel", "dragon"], "#aab9d6", "@ Assault Vest"), option("Ire-Foudre", "ire foudre", ["electric", "dragon"], "#ff9e42", "@ Booster Energy"),
  option("Salamence", "salamence", ["dragon", "flying"], "#67b6df"), option("Méga-Salamence", "mega_salamence", ["dragon", "flying"], "#67b6df"), option("Kingambit", "kingambit", ["dark", "steel"], "#51485f"), option("Méga-Garchomp", "mega_garchomp", ["dragon", "ground"], "#b16cec"), option("Méga-Garchomp Z", "mega_garchompZ", ["dragon", "ground"], "#b16cec"), option("Méga-Raichu Y", "mega_raichuY", ["electric"], "#ffe71c"),
  option("Sneazer", "sneazer", ["fighting", "poison"], "#be7ae5"), option("Indeedee Femelle", "indeedee_female", ["psychic", "normal"], "#c47ab1"), option("Golisopod", "golisopod", ["bug", "water"], "#62b9c8"), option("Méga-Golisopod", "mega_golisopod", ["bug", "steel"], "#62b9c8"), option("Floette Fleur Éternelle", "floette", ["fairy"], "#e987c5"), option("Méga-Floette", "mega_floette", ["fairy"], "#e987c5"), option("Farigiraf", "farigiraf", ["normal", "psychic"], "#bd7f55"), option("Pelipper", "pelipper", ["water", "flying"], "#8dc6e7"),
  option("Arcanine de Hisui", "arcanine hisuian", ["fire", "rock"], "#d97745"), option("Gholdengo", "gholdengo", ["steel", "ghost"], "#e3b929"), option("Charizard", "charizard", ["fire", "flying"], "#ef6a34"), option("Sylveon", "sylveon", ["fairy"], "#f2a4bf"), option("Méga-Charizard Y", "mega_charizardY", ["fire", "flying"], "#ef6a34"), option("Tyranitar", "tyranitar", ["rock", "dark"], "#7e9c48"), option("Gardevoir", "gardevoir", ["psychic", "fairy"], "#e9e5f5"), option("Méga-Gardevoir", "mega_gardevoir", ["psychic", "fairy"], "#e9e5f5"),
  option("Lucario", "lucario", ["fighting", "steel"], "#507ce0"), option("Whimsicott", "whimsicott", ["grass", "fairy"], "#b8e7a4"), option("Méga-Lucario", "mega_lucario", ["fighting", "steel"], "#507ce0"), option("Méga-Lucario Z", "mega_lucarioZ", ["fighting", "steel"], "#507ce0"), option("Raichu", "raichu", ["electric"], "#ffe71c"), option("Méga-Tyranitar", "mega_tyranitar", ["rock", "dark"], "#7e9c48"), option("Excadrill", "excadrill", ["ground", "steel"], "#a17965"), option("Torkoal", "torkoal", ["fire"], "#ce7051"), option("Armarouge", "armarouge", ["fire", "psychic"], "#cc5843"), option("Indeedee Mâle", "indeedee_male", ["psychic", "normal"], "#6e98df"),
  option("Baxcalibur", "baxcalibur", ["dragon", "ice"], "#65bde0"), option("Méga-Baxcalibur", "mega_baxcalibur", ["dragon", "ice"], "#65bde0"), option("Heatran", "heatran", ["fire", "steel"], "#bd6046"), option("Méga-Heatran", "mega_heatran", ["fire", "steel"], "#bd6046"), option("Absol", "absol", ["dark"], "#9e9aa7"), option("Méga-Absol", "mega_absol", ["dark"], "#9e9aa7"), option("Méga-Absol Z", "mega_absolZ", ["dark", "ghost"], "#9e9aa7"), option("Gyarados", "gyarados", ["water", "flying"], "#4c9bd4"), option("Méga-Gyarados", "mega_gyarados", ["water", "dark"], "#365fad"), option("Dragalge", "dragalge", ["poison", "dragon"], "#956ab9"), option("Méga-Dragalge", "mega_dragalge", ["poison", "dragon"], "#956ab9"),
  option("Scolipede", "scolipede", ["bug", "poison"], "#ba4e9a"), option("Méga-Scolipede", "mega_scolipede", ["bug", "poison"], "#ba4e9a"), option("Meganium", "meganium", ["grass"], "#77b95f"), option("Méga-Meganium", "mega_meganium", ["grass", "fairy"], "#77b95f"), option("Magearna", "magearna", ["steel", "fairy"], "#c3a6bd"), option("Méga-Magearna", "mega_magearna", ["steel", "fairy"], "#c3a6bd"), option("Starmie", "starmie", ["water", "psychic"], "#a977c8"), option("Méga-Starmie", "mega_starmie", ["water", "psychic"], "#a977c8"), option("Clefable", "clefable", ["fairy"], "#eaa9cf"), option("Méga-Clefable", "mega_clefable", ["fairy", "flying"], "#eaa9cf"), option("Eelektross", "eelektross", ["electric"], "#e0bc3e"), option("Méga-Eelektross", "mega_eelektross", ["electric"], "#e0bc3e"),
  option("Glalie", "glalie", ["ice"], "#9edbea"), option("Méga-Glalie", "mega_glalie", ["ice"], "#9edbea"), option("Chandelure", "chandelure", ["ghost", "fire"], "#7353b5"), option("Méga-Chandelure", "mega_chandelure", ["ghost", "fire"], "#7353b5"), option("Delphox", "delphox", ["fire", "psychic"], "#d85850"), option("Méga-Delphox", "mega_delphox", ["fire", "psychic"], "#d85850"), option("Staraptor", "staraptor", ["normal", "flying"], "#b56758"), option("Méga-Staraptor", "mega_staraptor", ["fighting", "flying"], "#b56758"), option("Darkrai", "darkrai", ["dark"], "#514b67"), option("Méga-Darkrai", "mega_darkrai", ["dark"], "#514b67"), option("Zeraora", "zeraora", ["electric"], "#f2c833"), option("Méga-Zeraora", "mega_zeraora", ["electric"], "#f2c833")
];

const typeNames = { normal: "Normal", fire: "Feu", water: "Eau", electric: "Électrik", grass: "Plante", ice: "Glace", fighting: "Combat", poison: "Poison", ground: "Sol", flying: "Vol", psychic: "Psy", bug: "Insecte", rock: "Roche", ghost: "Spectre", dragon: "Dragon", dark: "Ténèbres", steel: "Acier", fairy: "Fée" };
const slot = Number(new URLSearchParams(window.location.search).get("slot"));
const grid = document.querySelector("#replacement-grid");
grid.innerHTML = options.map((pokemon, index) => `<button class="replacement-card" data-option="${index}"><img src="${pokemon.image}" alt="${pokemon.name}"><span>${pokemon.name}</span><small>${pokemon.types.map((type) => typeNames[type]).join(" / ")}</small></button>`).join("");
grid.addEventListener("click", (event) => { const button = event.target.closest(".replacement-card"); if (!button || !Number.isInteger(slot) || slot < 0 || slot > 5) return; const team = JSON.parse(localStorage.getItem("pokemon-team") || "null") || [...Array(6)].map(() => null); team[slot] = options[Number(button.dataset.option)]; localStorage.setItem("pokemon-team", JSON.stringify(team)); window.location.href = "index.html"; });
