const gif = (file) => `images/gifs/${file}.gif`;
const moveSets = {
  "tapu koko": ["Thunderbolt", "Dazzling Gleam", "Reflect", "Light Screen"], rilaboom: ["Grassy Glide", "Wood Hammer", "Fake Out", "U-turn"], archaludon: ["Electro Shot", "Draco Meteor", "Flash Cannon", "Body Press"], "ire foudre": ["Thunderclap", "Draco Meteor", "Flamethrower", "Protect"],
  salamence: ["Draco Meteor", "Hurricane", "Tailwind", "Protect"], mega_salamence: ["Double-Edge", "Dragon Dance", "Earthquake", "Roost"], kingambit: ["Kowtow Cleave", "Sucker Punch", "Iron Head", "Swords Dance"], mega_garchomp: ["Dragon Claw", "Earthquake", "Rock Slide", "Protect"], mega_garchompZ: ["Scale Shot", "Earthquake", "Iron Head", "Swords Dance"], mega_raichuX: ["Fake Out", "Rising Voltage", "Volt Switch", "Protect"], mega_raichuY: ["Rising Voltage", "Fake Out", "Volt Switch", "Protect"], sneazer: ["Dire Claw", "Close Combat", "Knock Off", "Protect"],
  indeedee_female: ["Follow Me", "Helping Hand", "Expanding Force", "Protect"], golisopod: ["First Impression", "Liquidation", "Leech Life", "Protect"], mega_golisopod: ["First Impression", "Liquidation", "Sucker Punch", "Protect"], floette: ["Moonblast", "Mystical Fire", "Calm Mind", "Protect"], mega_floette: ["Moonblast", "Earth Power", "Calm Mind", "Protect"], farigiraf: ["Expanding Force", "Hyper Voice", "Trick Room", "Helping Hand"], pelipper: ["Hurricane", "Weather Ball", "Tailwind", "Wide Guard"],
  "arcanine hisuian": ["Rock Slide", "Flare Blitz", "Extreme Speed", "Protect"], gholdengo: ["Make It Rain", "Shadow Ball", "Recover", "Nasty Plot"], charizard: ["Heat Wave", "Air Slash", "Tailwind", "Protect"], sylveon: ["Hyper Voice", "Moonblast", "Calm Mind", "Protect"], mega_charizardY: ["Heat Wave", "Solar Beam", "Air Slash", "Protect"], tyranitar: ["Rock Slide", "Knock Off", "Low Kick", "Protect"], gardevoir: ["Moonblast", "Psychic", "Trick Room", "Protect"], mega_gardevoir: ["Hyper Voice", "Psyshock", "Focus Blast", "Calm Mind"],
  lucario: ["Close Combat", "Bullet Punch", "Extreme Speed", "Protect"], whimsicott: ["Moonblast", "Tailwind", "Encore", "Taunt"], mega_lucario: ["Close Combat", "Meteor Mash", "Extreme Speed", "Swords Dance"], mega_lucarioZ: ["Close Combat", "Flash Cannon", "Nasty Plot", "Vacuum Wave"], raichu: ["Fake Out", "Volt Switch", "Rising Voltage", "Protect"], mega_tyranitar: ["Rock Slide", "Crunch", "Low Kick", "Dragon Dance"], excadrill: ["Earthquake", "Iron Head", "Rock Slide", "Protect"], torkoal: ["Eruption", "Heat Wave", "Earth Power", "Protect"], armarouge: ["Armor Cannon", "Expanding Force", "Trick Room", "Wide Guard"], indeedee_male: ["Expanding Force", "Dazzling Gleam", "Helping Hand", "Protect"],
  baxcalibur: ["Glaive Rush", "Icicle Crash", "Ice Shard", "Dragon Dance"], mega_baxcalibur: ["Glaive Rush", "Icicle Crash", "Earthquake", "Dragon Dance"], heatran: ["Heat Wave", "Flash Cannon", "Earth Power", "Protect"], mega_heatran: ["Magma Storm", "Flash Cannon", "Earth Power", "Protect"], absol: ["Knock Off", "Sucker Punch", "Play Rough", "Swords Dance"], mega_absol: ["Knock Off", "Sucker Punch", "Play Rough", "Swords Dance"], mega_absolZ: ["Knock Off", "Sucker Punch", "Superpower", "Swords Dance"], gyarados: ["Waterfall", "Crunch", "Ice Fang", "Dragon Dance"], mega_gyarados: ["Waterfall", "Crunch", "Earthquake", "Dragon Dance"], dragalge: ["Draco Meteor", "Sludge Bomb", "Thunderbolt", "Protect"], mega_dragalge: ["Draco Meteor", "Sludge Wave", "Hydro Pump", "Protect"],
  scolipede: ["Megahorn", "Poison Jab", "Protect", "Speed Boost"], mega_scolipede: ["Megahorn", "Poison Jab", "Earthquake", "Swords Dance"], meganium: ["Giga Drain", "Leech Seed", "Reflect", "Synthesis"], mega_meganium: ["Giga Drain", "Moonblast", "Leech Seed", "Calm Mind"], magearna: ["Fleur Cannon", "Flash Cannon", "Volt Switch", "Trick Room"], mega_magearna: ["Fleur Cannon", "Aura Sphere", "Flash Cannon", "Calm Mind"], starmie: ["Hydro Pump", "Psychic", "Ice Beam", "Recover"], mega_starmie: ["Hydro Pump", "Psychic", "Thunderbolt", "Recover"], clefable: ["Moonblast", "Follow Me", "Helping Hand", "Protect"], mega_clefable: ["Moonblast", "Flamethrower", "Calm Mind", "Soft-Boiled"], eelektross: ["Thunderbolt", "Flamethrower", "Giga Drain", "Volt Switch"], mega_eelektross: ["Thunderbolt", "Draco Meteor", "Flamethrower", "Volt Switch"],
  glalie: ["Ice Spinner", "Earthquake", "Crunch", "Protect"], mega_glalie: ["Return", "Ice Shard", "Earthquake", "Explosion"], chandelure: ["Shadow Ball", "Heat Wave", "Trick Room", "Protect"], mega_chandelure: ["Shadow Ball", "Heat Wave", "Energy Ball", "Trick Room"], delphox: ["Heat Wave", "Psychic", "Dazzling Gleam", "Protect"], mega_delphox: ["Fire Blast", "Psyshock", "Focus Blast", "Nasty Plot"], staraptor: ["Brave Bird", "Double-Edge", "Close Combat", "U-turn"], mega_staraptor: ["Brave Bird", "Double-Edge", "Close Combat", "Quick Attack"], darkrai: ["Dark Pulse", "Dark Void", "Nasty Plot", "Sludge Bomb"], mega_darkrai: ["Dark Pulse", "Dark Void", "Focus Blast", "Nasty Plot"], zeraora: ["Plasma Fists", "Close Combat", "Fake Out", "Volt Switch"], mega_zeraora: ["Plasma Fists", "Close Combat", "Knock Off", "Bulk Up"]
};
const englishNames = { "Ire-Foudre": "Raging Bolt", "Floette Fleur Éternelle": "Eternal Flower Floette", "Indeedee Femelle": "Indeedee Female", "Indeedee Mâle": "Indeedee Male", "Arcanine de Hisui": "Hisuian Arcanine" };
const option = (name, file, types, accent, item = "@ Choice Band") => { const englishName = (englishNames[name] || name).replace(/^Méga-/i, "Mega-"); return { name: englishName, item: /^Mega-/i.test(englishName) ? `@ Mega Gem: ${englishName.replace(/^Mega-/i, "")}` : item, image: gif(file), accent, types, moves: moveSets[file] || ["Protect", "Tera Blast", "Knock Off", "U-turn"] }; };

// File names match the supplied GIFs. X, Y, and Z suffixes are kept as supplied.
const options = [
  option("Tapu Koko", "tapu koko", ["electric", "flying"], "#ffe71c", "@ Light Clay"), option("Rillaboom", "rilaboom", ["grass"], "#83d85d", "@ Miracle Seed"), option("Archaludon", "archaludon", ["steel", "dragon"], "#aab9d6", "@ Assault Vest"), option("Ire-Foudre", "ire foudre", ["electric", "dragon"], "#ff9e42", "@ Booster Energy"),
  option("Salamence", "salamence", ["dragon", "flying"], "#67b6df"), option("Méga-Salamence", "mega_salamence", ["dragon", "flying"], "#67b6df"), option("Kingambit", "kingambit", ["dark", "steel"], "#51485f"), option("Méga-Garchomp", "mega_garchomp", ["dragon", "ground"], "#b16cec"), option("Méga-Garchomp Z", "mega_garchompZ", ["dragon", "ground"], "#b16cec"), option("Méga-Raichu X", "mega_raichuX", ["electric"], "#ffe71c", "@ Raichuite X"), option("Méga-Raichu Y", "mega_raichuY", ["electric"], "#ffe71c"),
  option("Sneazer", "sneazer", ["fighting", "poison"], "#be7ae5"), option("Indeedee Femelle", "indeedee_female", ["psychic", "normal"], "#c47ab1"), option("Golisopod", "golisopod", ["bug", "water"], "#62b9c8"), option("Méga-Golisopod", "mega_golisopod", ["bug", "water"], "#62b9c8"), option("Floette Fleur Éternelle", "floette", ["fairy"], "#e987c5"), option("Méga-Floette", "mega_floette", ["fairy"], "#e987c5"), option("Farigiraf", "farigiraf", ["normal", "psychic"], "#bd7f55"), option("Pelipper", "pelipper", ["water", "flying"], "#8dc6e7"),
  option("Arcanine de Hisui", "arcanine hisuian", ["fire", "rock"], "#d97745"), option("Gholdengo", "gholdengo", ["steel", "ghost"], "#e3b929"), option("Charizard", "charizard", ["fire", "flying"], "#ef6a34"), option("Sylveon", "sylveon", ["fairy"], "#f2a4bf"), option("Méga-Charizard Y", "mega_charizardY", ["fire", "flying"], "#ef6a34"), option("Tyranitar", "tyranitar", ["rock", "dark"], "#7e9c48"), option("Gardevoir", "gardevoir", ["psychic", "fairy"], "#e9e5f5"), option("Méga-Gardevoir", "mega_gardevoir", ["psychic", "fairy"], "#e9e5f5"),
  option("Lucario", "lucario", ["fighting", "steel"], "#507ce0"), option("Whimsicott", "whimsicott", ["grass", "fairy"], "#b8e7a4"), option("Méga-Lucario", "mega_lucario", ["fighting", "steel"], "#507ce0"), option("Méga-Lucario Z", "mega_lucarioZ", ["fighting", "steel"], "#507ce0"), option("Raichu", "raichu", ["electric"], "#ffe71c"), option("Méga-Tyranitar", "mega_tyranitar", ["rock", "dark"], "#7e9c48"), option("Excadrill", "excadrill", ["ground", "steel"], "#a17965"), option("Torkoal", "torkoal", ["fire"], "#ce7051"), option("Armarouge", "armarouge", ["fire", "psychic"], "#cc5843"), option("Indeedee Mâle", "indeedee_male", ["psychic", "normal"], "#6e98df"),
  option("Baxcalibur", "baxcalibur", ["dragon", "ice"], "#65bde0"), option("Méga-Baxcalibur", "mega_baxcalibur", ["dragon", "ice"], "#65bde0"), option("Heatran", "heatran", ["fire", "steel"], "#bd6046"), option("Méga-Heatran", "mega_heatran", ["fire", "steel"], "#bd6046"), option("Absol", "absol", ["dark"], "#9e9aa7"), option("Méga-Absol", "mega_absol", ["dark"], "#9e9aa7"), option("Méga-Absol Z", "mega_absolZ", ["dark"], "#9e9aa7"), option("Gyarados", "gyarados", ["water", "flying"], "#4c9bd4"), option("Méga-Gyarados", "mega_gyarados", ["water", "dark"], "#365fad"), option("Dragalge", "dragalge", ["poison", "dragon"], "#956ab9"), option("Méga-Dragalge", "mega_dragalge", ["poison", "dragon"], "#956ab9"),
  option("Scolipede", "scolipede", ["bug", "poison"], "#ba4e9a"), option("Méga-Scolipede", "mega_scolipede", ["bug", "poison"], "#ba4e9a"), option("Meganium", "meganium", ["grass"], "#77b95f"), option("Méga-Meganium", "mega_meganium", ["grass", "fairy"], "#77b95f"), option("Magearna", "magearna", ["steel", "fairy"], "#c3a6bd"), option("Méga-Magearna", "mega_magearna", ["steel", "fairy"], "#c3a6bd"), option("Starmie", "starmie", ["water", "psychic"], "#a977c8"), option("Méga-Starmie", "mega_starmie", ["water", "psychic"], "#a977c8"), option("Clefable", "clefable", ["fairy"], "#eaa9cf"), option("Méga-Clefable", "mega_clefable", ["fairy"], "#eaa9cf"), option("Eelektross", "eelektross", ["electric"], "#e0bc3e"), option("Méga-Eelektross", "mega_eelektross", ["electric"], "#e0bc3e"),
  option("Glalie", "glalie", ["ice"], "#9edbea"), option("Méga-Glalie", "mega_glalie", ["ice"], "#9edbea"), option("Chandelure", "chandelure", ["ghost", "fire"], "#7353b5"), option("Méga-Chandelure", "mega_chandelure", ["ghost", "fire"], "#7353b5"), option("Delphox", "delphox", ["fire", "psychic"], "#d85850"), option("Méga-Delphox", "mega_delphox", ["fire", "psychic"], "#d85850"), option("Staraptor", "staraptor", ["normal", "flying"], "#b56758"), option("Méga-Staraptor", "mega_staraptor", ["normal", "flying"], "#b56758"), option("Darkrai", "darkrai", ["dark"], "#514b67"), option("Méga-Darkrai", "mega_darkrai", ["dark"], "#514b67"), option("Zeraora", "zeraora", ["electric"], "#f2c833"), option("Méga-Zeraora", "mega_zeraora", ["electric"], "#f2c833")
];

const typeNames = { normal: "Normal", fire: "Fire", water: "Water", electric: "Electric", grass: "Grass", ice: "Ice", fighting: "Fighting", poison: "Poison", ground: "Ground", flying: "Flying", psychic: "Psychic", bug: "Bug", rock: "Rock", ghost: "Ghost", dragon: "Dragon", dark: "Dark", steel: "Steel", fairy: "Fairy" };
const typeSearchTerms = Object.fromEntries(Object.entries(typeNames).map(([key, value]) => [key, `${key} ${value.toLowerCase()}`]));
const slot = Number(new URLSearchParams(window.location.search).get("slot"));
const grid = document.querySelector("#replacement-grid");
const search = document.querySelector("#pokemon-search");
const resultCount = document.querySelector("#result-count");
const normalize = (value) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
function renderOptions(query = "") { const term = normalize(query.trim()); const filtered = options.filter((pokemon) => !term || normalize(`${pokemon.name} ${pokemon.types.map((type) => `${type} ${typeNames[type]} ${typeSearchTerms[type]}`).join(" ")}`).includes(term)); grid.innerHTML = filtered.map((pokemon) => `<button class="replacement-card" data-option="${options.indexOf(pokemon)}"><img src="${pokemon.image}" alt="${pokemon.name}"><span>${pokemon.name}</span><small>${pokemon.types.map((type) => typeNames[type]).join(" / ")}</small></button>`).join(""); resultCount.textContent = `${filtered.length} Pokémon found`; }
renderOptions();
search.addEventListener("input", () => renderOptions(search.value));
grid.addEventListener("click", (event) => { const button = event.target.closest(".replacement-card"); if (!button || !Number.isInteger(slot) || slot < 0 || slot > 5) return; const team = JSON.parse(localStorage.getItem("pokemon-team") || "null") || [...Array(6)].map(() => null); team[slot] = options[Number(button.dataset.option)]; localStorage.setItem("pokemon-team", JSON.stringify(team)); window.location.href = "team.html"; });
