const typeInfo = {
  electric: { name: "Électrik", resistant: ["Électrik", "Vol", "Acier"], strong: ["Eau", "Vol"] }, water: { name: "Eau", resistant: ["Feu", "Eau", "Glace", "Acier"], strong: ["Feu", "Sol", "Roche"] }, flying: { name: "Vol", resistant: ["Plante", "Combat", "Insecte"], strong: ["Plante", "Combat", "Insecte"] }, fire: { name: "Feu", resistant: ["Feu", "Plante", "Glace", "Insecte", "Acier", "Fée"], strong: ["Plante", "Glace", "Insecte", "Acier"] }, dark: { name: "Ténèbres", resistant: ["Spectre", "Ténèbres"], strong: ["Spectre", "Psy"] }, ground: { name: "Sol", resistant: ["Poison", "Roche"], strong: ["Feu", "Électrik", "Poison", "Roche", "Acier"] }, dragon: { name: "Dragon", resistant: ["Feu", "Eau", "Plante", "Électrik"], strong: ["Dragon"] }, ghost: { name: "Spectre", resistant: ["Poison", "Insecte"], strong: ["Spectre", "Psy"] }, grass: { name: "Plante", resistant: ["Eau", "Électrik", "Plante", "Sol"], strong: ["Eau", "Sol", "Roche"] }, steel: { name: "Acier", resistant: ["Normal", "Plante", "Glace", "Vol", "Psy", "Insecte", "Roche", "Dragon", "Acier", "Fée"], strong: ["Glace", "Roche", "Fée"] }
};
Object.assign(typeInfo, {
  normal: { name: "Normal", resistant: [], strong: [] }, ice: { name: "Glace", resistant: ["Glace"], strong: ["Plante", "Sol", "Vol", "Dragon"] }, fighting: { name: "Combat", resistant: ["Insecte", "Roche", "Ténèbres"], strong: ["Normal", "Glace", "Roche", "Ténèbres", "Acier"] }, poison: { name: "Poison", resistant: ["Plante", "Combat", "Poison", "Insecte", "Fée"], strong: ["Plante", "Fée"] }, psychic: { name: "Psy", resistant: ["Combat", "Psy"], strong: ["Combat", "Poison"] }, bug: { name: "Insecte", resistant: ["Plante", "Combat", "Sol"], strong: ["Plante", "Psy", "Ténèbres"] }, rock: { name: "Roche", resistant: ["Normal", "Feu", "Poison", "Vol"], strong: ["Feu", "Glace", "Vol", "Insecte"] }, fairy: { name: "Fée", resistant: ["Combat", "Insecte", "Ténèbres"], strong: ["Combat", "Dragon", "Ténèbres"] }
});
const moveChoices = ["Protect", "Thunderbolt", "Volt Switch", "Fake Out", "Helping Hand", "Tera Blast", "Substitute", "Taunt", "Ice Punch", "Knock Off", "U-turn", "Earthquake"];
const tooltip = document.querySelector("#type-tooltip");
function showTooltip(type, target) { const info = typeInfo[type]; if (!info) return; tooltip.innerHTML = `<strong>${info.name}</strong><span><b>Résiste à :</b> ${info.resistant.join(", ")}</span><span><b>Super efficace contre :</b> ${info.strong.join(", ")}</span>`; const bounds = target.getBoundingClientRect(); tooltip.style.left = `${Math.min(bounds.left, window.innerWidth - 245)}px`; tooltip.style.top = `${bounds.bottom + 8}px`; tooltip.classList.add("is-visible"); tooltip.setAttribute("aria-hidden", "false"); }
function hideTooltip() { tooltip.classList.remove("is-visible"); tooltip.setAttribute("aria-hidden", "true"); }
function saveTeam() { const team = [...document.querySelectorAll(".pokemon-card")].map((card) => ({ name: card.querySelector("h1").textContent, item: card.querySelector(".pokemon-heading span").textContent, image: card.querySelector(".sprite").getAttribute("src"), accent: card.dataset.accent, types: [...card.querySelectorAll(".type")].map((type) => type.classList[1]), moves: [...card.querySelectorAll(".moves li")].map((move) => move.textContent) })); localStorage.setItem("pokemon-team", JSON.stringify(team)); }
function restoreTeam() { const saved = JSON.parse(localStorage.getItem("pokemon-team") || "null"); if (!saved) return; document.querySelectorAll(".pokemon-card").forEach((card, index) => { const pokemon = saved[index]; if (!pokemon) return; card.dataset.accent = pokemon.accent; card.querySelector("h1").textContent = pokemon.name; card.querySelector(".pokemon-heading span").textContent = pokemon.item; card.querySelector(".sprite").src = pokemon.image; card.querySelector(".sprite").alt = pokemon.name; card.querySelector(".types").innerHTML = pokemon.types.map((type) => `<span class="type ${type}">${typeInfo[type] ? typeInfo[type].name : type}</span>`).join(""); card.querySelector(".moves").innerHTML = pokemon.moves.map((move) => `<li>${move}</li>`).join(""); }); }
function openMoveSelect(move) { if (move.querySelector("select")) return; const currentMove = move.textContent; const select = document.createElement("select"); select.className = "move-select"; select.setAttribute("aria-label", "Choisir une attaque"); [currentMove, ...moveChoices.filter((choice) => choice !== currentMove)].forEach((choice) => select.add(new Option(choice, choice))); move.textContent = ""; move.append(select); select.focus(); const close = () => { move.textContent = select.value; saveTeam(); }; select.addEventListener("change", close); select.addEventListener("blur", close); }
function addInteractions() { document.querySelectorAll(".pokemon-card").forEach((card) => { card.style.setProperty("--accent", card.dataset.accent || "#d970ff"); card.addEventListener("pointermove", (event) => { const bounds = card.getBoundingClientRect(); const x = ((event.clientX - bounds.left) / bounds.width) * 100; const y = ((event.clientY - bounds.top) / bounds.height) * 100; card.style.setProperty("--mouse-x", `${x}%`); card.style.setProperty("--mouse-y", `${y}%`); card.style.transform = `perspective(800px) rotateX(${(50 - y) / 22}deg) rotateY(${(x - 50) / 18}deg) translateY(-3px)`; }); card.addEventListener("pointerleave", () => { card.style.transform = ""; }); card.addEventListener("click", (event) => { if (event.target.closest(".type") || event.target.closest(".moves li") || event.target.closest("select")) return; window.location.href = `replacement.html?slot=${card.dataset.slot}`; }); card.addEventListener("keydown", (event) => { if (event.key === "Enter") window.location.href = `replacement.html?slot=${card.dataset.slot}`; }); }); document.addEventListener("click", (event) => { const move = event.target.closest(".moves li"); if (move) openMoveSelect(move); }); document.addEventListener("pointerover", (event) => { const type = event.target.closest(".type"); if (type) showTooltip(type.classList[1], type); }); document.addEventListener("pointerout", (event) => { if (event.target.closest(".type")) hideTooltip(); }); }
restoreTeam(); addInteractions();
